# Generated by Django 4.0.3 on 2022-03-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='number',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
    ]
