# Generated by Django 4.0.3 on 2022-03-25 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='message',
            new_name='info',
        ),
    ]
