# Generated by Django 4.0.3 on 2022-03-27 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_rename_message_day_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='last_updated',
            new_name='last_changed',
        ),
    ]
