# Generated by Django 4.0.3 on 2022-03-27 23:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_rename_last_updated_day_last_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime.now),
            preserve_default=False,
        ),
    ]
