# Generated by Django 4.0.3 on 2022-03-28 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0005_alter_day_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='info',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
