# Generated by Django 4.0.3 on 2022-03-31 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0007_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='teacher',
            field=models.ForeignKey(default='N/A', on_delete=django.db.models.deletion.SET_DEFAULT, to='plan.teacher'),
        ),
    ]
