# Generated by Django 4.0.3 on 2022-03-31 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0008_alter_period_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plan.teacher'),
        ),
    ]
