# Generated by Django 4.0.3 on 2023-08-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0012_day_date_as_string_period_change_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='room',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='short_name',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
