# Generated by Django 4.0.3 on 2023-08-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0015_remove_day_date_as_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='date_as_string',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
