# Generated by Django 4.0.3 on 2023-08-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0016_day_date_as_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='date_as_string',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
