# Generated by Django 4.0.3 on 2023-08-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0017_alter_day_date_as_string'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
    ]
