# Generated by Django 4.0.3 on 2023-08-13 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0018_freeday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='last_changed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
