# Generated by Django 4.0.3 on 2023-08-13 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0019_alter_day_last_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='is_empty',
            field=models.BooleanField(default=False),
        ),
    ]
