# Generated by Django 4.0.3 on 2025-05-26 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0020_day_is_empty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='subject',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='period',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plan.teacher'),
        ),
    ]
