name: publish

on: [push]

jobs:
  publish-planplus-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the planplus Docker image
      run: |
        docker build . --tag ghcr.io/dominikkor/planplus:latest
        docker push ghcr.io/dominikkor/planplus:latest
